title: Try again. Fail better.
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: http://brianmaierjr.github.com/long-haul
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /home
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: jungtae9lee
   facebook: vidkidsy
   email: clickmax85@gmail.com

google_analytics: "UA-58263416-1"
